# Config for GRN set to simulate SERGIO configuration
grn:
  ## Simulation related
  n_cells: 250
  delta: 0.01
  n_steps: 20
  config_file: "configs/sample_data/sample_network_1cell.yaml"
  random_key: 42
  logging: true
  learn_params: false
  epochs: 10
  
  ## Gene related
  non_mr_basal: false
  noise: false
  noise_amplitude: 0.1
  decay:
    - 0.8
  hill_coeffs:
    - 1.0

  ## Protein related
  protein_sim: false
  
# Lattice free setup
spatial_sim:
  ## Mesh related
  height: 5
  width: 5
  depth: 5
  mesh_type: "lattice-free"
  field_resolution: 2 # Divide into X divisions along each axis
  cell_concentration: 2 # Default value is 10
  field_vol: 1.0
  n_cell_type: 1
  cell_qty:
    cell1: 1.0

  ## Diffusion related
  D: 0.5
  diffusion_bool: true
  n_neighbours: 3
  
  ## Simulation Related
  delta: 0.01
  n_steps: 20
  random_key: 42
  logging: true

  ## Movement related
  movement_bool: true
  movement:
    cell1:
      qty_ratio: 1.0
      attraction_coeff: 2
      repulsion_coeff: 0.1
      drift_vel_coeff: 0
      random_vel_coeff: 0

  ## Cycle related
  cycle_bool: true
  cycle:
    cell1:
      cycle_len: 10
      interphase_len: 0.9

      necrosis_death_prob: 0.1
      apoptosis_death_prob: 0.1
      cell_decay_rate: 0.5
      
      cell_target_vol: 10.0
      cell_density: 1.0
      cell_vol_growth_rate: 1.0
  
  ## Chemicals
  chemical:
    name:
      - "chem1"
      - "chem2"
      - "chem3"
    mol_mass:
      - 1
      - 2
      - 3
  
  ## Reactions
  reaction_bool: true
  reaction_prob: false
  reaction:
    reac_2: # Production of chemical
      order: 0
      rate_coeff: 1
      reactants:
      reactants_exponent:
      products:
        - "chem3"
      products_exponent:
        - 3
    reac_3: # Reaction of chemicals
      order: 2
      rate_coeff: 0.2
      reactants:
        - "chem3"
        - "chem1"
      reactants_exponent:
        - 1
        - 1
      products:
        - "chem2"
      products_exponent:
        - 1