defaults:
  - _self_
grn:
  n_cells: 2
  delta: 0.05
  n_steps: 200
  config_file: "configs/sample_data/bistable_network.yaml"
  random_key: 42
  logging: false
  learn_params: false
  epochs: 100
  lr: 0.1
  non_mr_basal: false
  noise: false
  noise_amplitude: 0.1
  decay:
    - 1.0
  hill_coeffs:
    - 2.0
  protein_sim: false
