defaults:
  - _self_
grn:
  ## Simulation related
  n_cells: 8
  delta: 0.01
  n_steps: 10
  config_file: "configs/sample_data/sample_network_1cell.yaml"
  random_key: 42
  logging: true
  log_dir: "logs"
  learn_params: false
  epochs: 0
  lr: 0.01

  ## Gene related
  non_mr_basal: false
  noise: false
  noise_amplitude: 0.1
  decay:
    - 0.8
  hill_coeffs:
    - 1.0

  ## Protein related
  protein_sim: true

# Lattice free setup
spatial_sim:
  ## Mesh related
  height: 2
  width: 2
  depth: 2
  mesh_type: "lattice-free"
  field_resolution: 2 # Divide into X divisions along each axis
  cell_concentration: 1 # Default value is 10
  field_vol: 1.0
  n_cell_type: 2

  ## Diffusion related
  # D: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
  D: 0.2
  diffusion_bool: false
  n_neighbours: 1

  ## Simulation Related
  delta: 0.01
  n_steps: 10
  random_key: 42
  logging: true
  log_dir: "logs"

  ## Movement related
  movement_bool: true
  movement:
    cell1:
      qty_ratio: 0.6
      attraction_coeff: 1
      repulsion_coeff: 0.1
      drift_vel_coeff: 0.01
      random_vel_coeff: 0.01
    cell2:
      qty_ratio: 0.4
      attraction_coeff: 2
      repulsion_coeff: 0.2
      drift_vel_coeff: 0.02
      random_vel_coeff: 0.05

  ## Cycle related
  cycle_bool: true
  cycle:
    cell1:
      cycle_len: 10
      interphase_len: 0.9
      necrosis_death_prob: 0.0001
      apoptosis_death_prob: 0.001
      cell_target_vol: 1.0
      cell_density: 1.0
      cell_vol_growth_rate: 1.0
      cell_decay_rate: 0.5
      resource_limit: [["chem1", 0.1]] # Chemical name and minimum value of the chemical for cell division
      contact_limit: [3, 0.5] # Maximum number of neighbours in the surrounding to perform cell division. Higher number of neighbours prevent cell division, radial limit
    cell2:
      cycle_len: 20
      interphase_len: 0.8
      necrosis_death_prob: 0.0001
      apoptosis_death_prob: 0.001
      cell_target_vol: 2.0
      cell_density: 2.0
      cell_vol_growth_rate: 1.5
      cell_decay_rate: 0.5

  ## Chemicals
  chemical:
    name:
      - "chem1"
      - "chem2"
      - "chem3"
    mol_mass:
      - 1
      - 2
      - 3

  ## Reactions
  reaction_bool: true
  reaction_prob: false
  reaction:
    reac_3: # Decay of chemical
      order: 0
      rate_coeff: 1
      reactants:
        - "chem2"
      reactants_exponent:
        - 3
      products:
      products_exponent:

intervention:
  random_key: 42
  spatial_sim:
    - - "cell_target_vol"
      - ["soft", "shift", 0.1]
      - ["loop", 1, 2, 4] # Type(Loop), Loop start time, loop length, gap between loops
      - ["index", [1, 2, 3]]
    - - "cell_residual_vel"
      - ["hard", [[0.1, 0.2, 0.3]]]
      - ["scheduled", 2]
      - ["index", [1, 2, 3]]
  grn:
    - - "decay"
      - ["hard", 0.8]
      - ["scheduled", 1] # Type(Loop), Loop start time, loop length, gap between loops
      - ["global"]
  other: ## Add_cell intervention - Data required - Time, cell config
    - - "add_cell"
      - ["scheduled", 2] # Temporal param
      - [[1, 1, 1], 0, 0.4, 0] ## Other Params - Position, cell_state of new cell, radius of new cell, parent cell id (to inherit other cell related parameters)
    - - "ablate" ## alias remove_cell
      - ["scheduled", 2]
      - [[2], -1] # Cell id, Death type (-1 for sudden death, -2 for programmed cell death)
    - - "add_particle"
      - ["scheduled", 3]
      - [[0.1, 0.1, 0.1], 0, 0.1] # Pos, Chemical, Ratio of increase/decrease
    - - "remove_particle"
      - ["scheduled", 8]
      - [[0.1, 0.1, 0.1], 0] # Location, chemical_id
    - - "set_particle"
      - ["scheduled", 5]
      - [[0.1, 0.1, 0.1], 0, 0.4] # Location, chemical_id, new rate
    - - "modify_edge" # Also adds edge
      - ["scheduled", 3]
      - [0, 1, -5.0, 0.2] # Target gene, Regulator Gene, Weight of new edge, probability of adding edge (computed as probability of selecting eac cell)
    - - "block_edge"
      - ["scheduled", 3]
      - [0, 10, 0.3] # Target gene, Regulator gene, Probability (k) of selecting each cell
      - ["scheduled", 1]
      - [[0.1, 0.1, 0.1], 0, 0.1]
    - - "add_reaction"
      - ["scheduled", 1]
      - - reac_4:
            order: 2
            rate_coeff: 1
            reactants:
              - "chem2"
            reactants_exponent:
              - 3
            products:
              - "chem1"
            products_exponent:
              - 1
          # Reaction name, all details in a dict again
