
# Config for GRN set to simulate SERGIO configuration
grn:
  ## Simulation related
  n_cells: 2
  delta: 0.01
  n_steps: 10
  config_file: "configs/sample_data/sample_network_2cell.yaml"
  random_key: 42
  logging: false
  
  ## Gene related
  non_mr_basal: false
  noise: false
  noise_amplitude: 0.1
  decay:
    - 0.8
  hill_coeffs:
    - 1.0

  ## Protein related
  protein_sim: false
  

spatial_sim:
  ## Mesh related
  height: 3
  width: 3
  depth: 3
  mesh_type: "grid"
  sparse_cells: true
  cell_num: 10

  ## Diffusion related
  D: 0.5
  diffusion_bool: true
  
  ## Simulation Related
  delta: 0.01
  n_steps: 10
  random_key: 42
  logging: true
  
  ## Chemicals
  chemical:
    name:
      - "chem1"
      - "chem2"
      - "chem3"
    mol_mass:
      - 1
      - 2
      - 3
  
  ## Reactions
  reaction_bool: true
  reaction_prob: false
  reaction:
    reac_2: # Production of chemical
      order: 0
      rate_coeff: 1
      reactants:
      reactants_exponent:
      products:
        - "chem3"
      products_exponent:
        - 3
    reac_3: # Decay of chemical
      order: 0
      rate_coeff: 1
      reactants:
        - "chem2"
      reactants_exponent:
        - 3
      products:
      products_exponent: