- - ki:
    - - -20.0
    - - -20.0
    - - -20.0
    type: g
  - ki:
    - - -20.0
    - - -20.0
    - - -20.0
    type: g
  - ki:
    - - -20.0
    - - -20.0
    - - -20.0
    type: g
- - - 2
    - 0
  - - 0
    - 1
  - - 1
    - 2
